### ISSUE TITLE
Withdrawal from some colophons

### ISSUE THREAD

**Issue by igneus** [jakubjelinek/Editio-Sti-Wolfgangi#1]
Hi,

I decided to withdraw from colophons of some booklets - (1) those that I haven't even touched and (2) those that have been subjected to custom "liturgical reforms".

As Github doesn't know anything about our repos sharing the historical content, I would like to ask you for a favor: please, merge my branch withdraw_from_colophons https://github.com/igneus/Editio-Sti-Wolfgangi/tree/withdraw_from_colophons (which is based on your fresh master) into your master.

**Comment by jakubjelinek** [comment]
I've merged your branch, though I think it is a pitty not to acknowledge the huge amount of work you've done on it.  So if you ever change your mind, you'll be welcome back in the colophons.

**Comment by igneus** [comment]
Thanks for the merge.

"The huge amount of my work" is acknowledged enough in the booklets already printed and in the git history.
