### ISSUE TITLE
feria II hebd XI 

### ISSUE THREAD

**Issue by Avika1804** [jakubjelinek/Editio-Sti-Wolfgangi#454]
[feria II-XI-Antonii.docx](https://github.com/jakubjelinek/Editio-Sti-Wolfgangi/files/8882379/feria.II-XI-Antonii.docx)

**Comment by Avika1804** [comment]
Does it work like that, or is unreadable?

**Comment by jakubjelinek** [comment]
Just arrived (to Bern), starting on it now.

**Comment by Avika1804** [comment]
Great! But eat first ;-)
Le sam. 11 juin 2022 à 22:28, Jakub Jelínek ***@***.***> a
écrit :

**Comment by jakubjelinek** [comment]
Uploaded now.

**Comment by Avika1804** [comment]
Great! Thank you!
There is a very nice mass (VO, FSSP) in Fribourg, would you like the address?
Or maybe in Hauterive (monks, Cist)

Good night and hear you soon!

Isabelle

**Comment by jakubjelinek** [comment]
I think my son wouldn't prefer VO.
We chose french mass at Dreifaltigkeit kirche in Bern so that we can walk around Bern a little bit before and it is Holy Trinity feast...
